//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contact()
        {
            this.Category = new HashSet<Category>();
        }
    
        public int Id { get; set; }
        public string ContectCategoryName { get; set; }
        public string ContectFirstTitle { get; set; }
        public string ContectLastTitle { get; set; }
        public string ContectImage { get; set; }
        public string ContectFullName { get; set; }
        public string ContectMail { get; set; }
        public string ContectCourse { get; set; }
        public string ContectButtonTitle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Category { get; set; }
    }
}
