//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Home()
        {
            this.Category = new HashSet<Category>();
        }
    
        public int Id { get; set; }
        public string HomeCategoryName { get; set; }
        public string HomeImage { get; set; }
        public string HomeFirsTitle { get; set; }
        public string HomeLastTitle { get; set; }
        public string HomeButtonTitle { get; set; }
        public string HomeStundentImg { get; set; }
        public string HomeNumberOfStudents { get; set; }
        public string HomeCourseImg { get; set; }
        public string HomeNumberOfCourses { get; set; }
        public string HomeTeacherImg { get; set; }
        public string HomeNumberOfTeachers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Category { get; set; }
    }
}
