//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MuratErenNarDatabaseEntities : DbContext
    {
        public MuratErenNarDatabaseEntities()
            : base("name=MuratErenNarDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> About { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Home> Home { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<WebVideoCourses> WebVideoCourses { get; set; }
        public virtual DbSet<BackendVideoCourse> BackendVideoCourse { get; set; }
        public virtual DbSet<SMManagement> SMManagement { get; set; }
        public virtual DbSet<ChemistryAndBiology> ChemistryAndBiology { get; set; }
        public virtual DbSet<GraphicDesingCourse> GraphicDesingCourse { get; set; }
        public virtual DbSet<EnglishCourse> EnglishCourse { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
