//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.Category = new HashSet<Category>();
        }
    
        public int Id { get; set; }
        public string TeacherCategoryName { get; set; }
        public string TeacherFirstTitle { get; set; }
        public string TeacherLastTitle { get; set; }
        public virtual HttpPostedFileBase imgFile { get; set; }
        [Required]
        [Display(Name = "Resimler")]
        public string TeacherImage { get; set; }
        [Required]
        [Display(Name = "Ad Soyad")]
        public string TeacherFullName { get; set; }
        [Required]
        [Display(Name = "Branþ")]
        public string TeacherProfession { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Category { get; set; }
    }
}
