//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebVideoCourses
    {
        public int VideoCourseId { get; set; }
        public string VideoCourseFirstTitle { get; set; }
        public string VideoCourseLastTitle { get; set; }
        public string VideoCoursePath { get; set; }
    }
}
